"""fix

Revision ID: 06103c3aff7c
Revises: 2e3fe10692e0
Create Date: 2024-12-13 19:26:51.300557

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '06103c3aff7c'
down_revision: Union[str, None] = '2e3fe10692e0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_diary_summary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('day', sa.Date(), nullable=True),
    sa.Column('sum_proteins', sa.Float(), nullable=True),
    sa.Column('sum_fats', sa.Float(), nullable=True),
    sa.Column('sum_carbohydrates', sa.Float(), nullable=True),
    sa.Column('sum_calories', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_diary_summary_day'), 'users_diary_summary', ['day'], unique=True)
    op.create_index(op.f('ix_users_diary_summary_id'), 'users_diary_summary', ['id'], unique=False)
    op.create_index(op.f('ix_users_diary_summary_user_id'), 'users_diary_summary', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_diary_summary_user_id'), table_name='users_diary_summary')
    op.drop_index(op.f('ix_users_diary_summary_id'), table_name='users_diary_summary')
    op.drop_index(op.f('ix_users_diary_summary_day'), table_name='users_diary_summary')
    op.drop_table('users_diary_summary')
    # ### end Alembic commands ###
