"""fix bug

Revision ID: 0cbf1e5622de
Revises: 999717c8d238
Create Date: 2024-12-10 22:41:27.207736

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0cbf1e5622de'
down_revision: Union[str, None] = '999717c8d238'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_diary', 'count',
               existing_type=sa.FLOAT(),
               type_=sa.Integer(),
               existing_nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users_diary', 'count',
               existing_type=sa.Integer(),
               type_=sa.FLOAT(),
               existing_nullable=True)
    # ### end Alembic commands ###
