"""add diary table

Revision ID: 2415b9441d89
Revises: 9834cea6b1f2
Create Date: 2024-12-09 17:40:51.509764

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2415b9441d89'
down_revision: Union[str, None] = '9834cea6b1f2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users_diary',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.Column('date', sa.Date(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_diary_id'), 'users_diary', ['id'], unique=False)
    op.create_index(op.f('ix_users_diary_user_id'), 'users_diary', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_diary_user_id'), table_name='users_diary')
    op.drop_index(op.f('ix_users_diary_id'), table_name='users_diary')
    op.drop_table('users_diary')
    # ### end Alembic commands ###
