"""edit date->day

Revision ID: 27fbd67605ed
Revises: 2415b9441d89
Create Date: 2024-12-09 18:10:43.028578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '27fbd67605ed'
down_revision: Union[str, None] = '2415b9441d89'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_diary', sa.Column('day', sa.Date(), nullable=True))
    op.drop_column('users_diary', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_diary', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('users_diary', 'day')
    # ### end Alembic commands ###
