"""вday column not unique

Revision ID: 70898f1cf66c
Revises: 06103c3aff7c
Create Date: 2024-12-14 16:36:33.627988

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '70898f1cf66c'
down_revision: Union[str, None] = '06103c3aff7c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_users_diary_summary_day', table_name='users_diary_summary')
    op.create_index(op.f('ix_users_diary_summary_day'), 'users_diary_summary', ['day'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_users_diary_summary_day'), table_name='users_diary_summary')
    op.create_index('ix_users_diary_summary_day', 'users_diary_summary', ['day'], unique=True)
    # ### end Alembic commands ###
