"""init

Revision ID: 8ca62de4fa26
Revises: 
Create Date: 2024-12-13 01:26:44.822654

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8ca62de4fa26'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint('products_user_id_fkey', 'products', type_='foreignkey')
    op.create_foreign_key(None, 'products', 'users', ['user_id'], ['id'])
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.alter_column('users_diary', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_diary', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('users_diary', 'count',
               existing_type=sa.INTEGER(),
               type_=sa.Float(),
               nullable=True)
    op.alter_column('users_diary', 'day',
               existing_type=sa.DATE(),
               nullable=True)
    op.drop_constraint('users_diary_user_id_fkey', 'users_diary', type_='foreignkey')
    op.drop_constraint('users_diary_product_id_fkey', 'users_diary', type_='foreignkey')
    op.create_foreign_key(None, 'users_diary', 'products', ['product_id'], ['id'])
    op.create_foreign_key(None, 'users_diary', 'users', ['user_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users_diary', type_='foreignkey')
    op.drop_constraint(None, 'users_diary', type_='foreignkey')
    op.create_foreign_key('users_diary_product_id_fkey', 'users_diary', 'products', ['product_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key('users_diary_user_id_fkey', 'users_diary', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users_diary', 'day',
               existing_type=sa.DATE(),
               nullable=False)
    op.alter_column('users_diary', 'count',
               existing_type=sa.Float(),
               type_=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_diary', 'product_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users_diary', 'user_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('users', 'hash_password',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'email',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.alter_column('users', 'username',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_constraint(None, 'products', type_='foreignkey')
    op.create_foreign_key('products_user_id_fkey', 'products', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.alter_column('products', 'name',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
