"""fix bug

Revision ID: 953ca867d6d4
Revises: 0cbf1e5622de
Create Date: 2024-12-10 22:41:55.263790

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '953ca867d6d4'
down_revision: Union[str, None] = '0cbf1e5622de'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_diary', sa.Column('count', sa.Integer(), nullable=True))
    op.add_column('users_diary', sa.Column('day', sa.Date(), nullable=True))
    op.drop_column('users_diary', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_diary', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('users_diary', 'day')
    op.drop_column('users_diary', 'count')
    # ### end Alembic commands ###
