"""fix bug

Revision ID: 999717c8d238
Revises: 27fbd67605ed
Create Date: 2024-12-10 22:25:35.702594

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '999717c8d238'
down_revision: Union[str, None] = '27fbd67605ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_diary', sa.Column('count', sa.Float(), nullable=True))
    op.add_column('users_diary', sa.Column('day', sa.Date(), nullable=True))
    op.drop_column('users_diary', 'date')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users_diary', sa.Column('date', sa.DATE(), nullable=True))
    op.drop_column('users_diary', 'day')
    op.drop_column('users_diary', 'count')
    # ### end Alembic commands ###
